
development:
 adapter: postgresql
 encoding: unicode
 database: hyperloop-showcase-template-heroku
 pool: 5
 username: fcooker
 password: Beloos-27021975

production:
  adapter: postgresql
  encoding: unicode
  database: hyperloop-showcase-template-heroku_production
  username: hyperloop-showcase-template-heroku
  password: <%= ENV['HYPERLOOP-SHOWCASE-TEMPLATE-HEROKU_DATABASE_PASSWORD'] %>